### ISSUE TITLE
为啥我这启动项目都是bug

### ISSUE THREAD

**Issue by chenyijie-bit** [hu-snail/arco-admin-template#1]
mock的接口是不是不能用  我这显示着好多问题 是我哪里操作不对吗

**Comment by hu-snail** [comment]
我还没正式发布，在调试问题，修复好了再通知你

**Comment by hu-snail** [comment]
> mock的接口是不是不能用 我这显示着好多问题 是我哪里操作不对吗

我还没正式发布，在调试问题，修复好了再通知你
